/*************************************************************
 * UlteSoft WebAssembly Virtual Machine (Version 2)            *
 * Licensed under the APL-2.0 License (see LICENSE file).      *
 *************************************************************/

#pragma once

// LLVM declares Mach-O constants as C++ names; Darwin's mach headers use
// macros with the same spellings. Include order must not change whether
// the JIT section manager builds. Temporarily shield only those names,
// restoring every host definition afterward. In particular do not undefine
// BYTE_ORDER/BIG_ENDIAN: LLVM uses them to select struct bitfield layout.
// Keep this wrapper in named modules' global fragments too, not after export.

#pragma push_macro("ARM_DEBUG_STATE")
#undef ARM_DEBUG_STATE
#pragma push_macro("ARM_EXCEPTION_STATE")
#undef ARM_EXCEPTION_STATE
#pragma push_macro("ARM_EXCEPTION_STATE64")
#undef ARM_EXCEPTION_STATE64
#pragma push_macro("ARM_THREAD_STATE")
#undef ARM_THREAD_STATE
#pragma push_macro("ARM_THREAD_STATE64")
#undef ARM_THREAD_STATE64
#pragma push_macro("ARM_THREAD_STATE64_COUNT")
#undef ARM_THREAD_STATE64_COUNT
#pragma push_macro("ARM_THREAD_STATE_COUNT")
#undef ARM_THREAD_STATE_COUNT
#pragma push_macro("ARM_VFP_STATE")
#undef ARM_VFP_STATE
#pragma push_macro("CPU_ARCH_ABI64")
#undef CPU_ARCH_ABI64
#pragma push_macro("CPU_ARCH_ABI64_32")
#undef CPU_ARCH_ABI64_32
#pragma push_macro("CPU_ARCH_MASK")
#undef CPU_ARCH_MASK
#pragma push_macro("CPU_SUBTYPE_386")
#undef CPU_SUBTYPE_386
#pragma push_macro("CPU_SUBTYPE_486")
#undef CPU_SUBTYPE_486
#pragma push_macro("CPU_SUBTYPE_486SX")
#undef CPU_SUBTYPE_486SX
#pragma push_macro("CPU_SUBTYPE_586")
#undef CPU_SUBTYPE_586
#pragma push_macro("CPU_SUBTYPE_ARM64E")
#undef CPU_SUBTYPE_ARM64E
#pragma push_macro("CPU_SUBTYPE_ARM64_32_V8")
#undef CPU_SUBTYPE_ARM64_32_V8
#pragma push_macro("CPU_SUBTYPE_ARM64_ALL")
#undef CPU_SUBTYPE_ARM64_ALL
#pragma push_macro("CPU_SUBTYPE_ARM64_V8")
#undef CPU_SUBTYPE_ARM64_V8
#pragma push_macro("CPU_SUBTYPE_ARM_ALL")
#undef CPU_SUBTYPE_ARM_ALL
#pragma push_macro("CPU_SUBTYPE_ARM_V4T")
#undef CPU_SUBTYPE_ARM_V4T
#pragma push_macro("CPU_SUBTYPE_ARM_V5TEJ")
#undef CPU_SUBTYPE_ARM_V5TEJ
#pragma push_macro("CPU_SUBTYPE_ARM_V6")
#undef CPU_SUBTYPE_ARM_V6
#pragma push_macro("CPU_SUBTYPE_ARM_V6M")
#undef CPU_SUBTYPE_ARM_V6M
#pragma push_macro("CPU_SUBTYPE_ARM_V7")
#undef CPU_SUBTYPE_ARM_V7
#pragma push_macro("CPU_SUBTYPE_ARM_V7EM")
#undef CPU_SUBTYPE_ARM_V7EM
#pragma push_macro("CPU_SUBTYPE_ARM_V7K")
#undef CPU_SUBTYPE_ARM_V7K
#pragma push_macro("CPU_SUBTYPE_ARM_V7M")
#undef CPU_SUBTYPE_ARM_V7M
#pragma push_macro("CPU_SUBTYPE_ARM_V7S")
#undef CPU_SUBTYPE_ARM_V7S
#pragma push_macro("CPU_SUBTYPE_ARM_XSCALE")
#undef CPU_SUBTYPE_ARM_XSCALE
#pragma push_macro("CPU_SUBTYPE_CELERON")
#undef CPU_SUBTYPE_CELERON
#pragma push_macro("CPU_SUBTYPE_CELERON_MOBILE")
#undef CPU_SUBTYPE_CELERON_MOBILE
#pragma push_macro("CPU_SUBTYPE_I386_ALL")
#undef CPU_SUBTYPE_I386_ALL
#pragma push_macro("CPU_SUBTYPE_INTEL")
#undef CPU_SUBTYPE_INTEL
#pragma push_macro("CPU_SUBTYPE_INTEL_FAMILY")
#undef CPU_SUBTYPE_INTEL_FAMILY
#pragma push_macro("CPU_SUBTYPE_INTEL_FAMILY_MAX")
#undef CPU_SUBTYPE_INTEL_FAMILY_MAX
#pragma push_macro("CPU_SUBTYPE_INTEL_MODEL")
#undef CPU_SUBTYPE_INTEL_MODEL
#pragma push_macro("CPU_SUBTYPE_INTEL_MODEL_ALL")
#undef CPU_SUBTYPE_INTEL_MODEL_ALL
#pragma push_macro("CPU_SUBTYPE_ITANIUM")
#undef CPU_SUBTYPE_ITANIUM
#pragma push_macro("CPU_SUBTYPE_ITANIUM_2")
#undef CPU_SUBTYPE_ITANIUM_2
#pragma push_macro("CPU_SUBTYPE_LIB64")
#undef CPU_SUBTYPE_LIB64
#pragma push_macro("CPU_SUBTYPE_MASK")
#undef CPU_SUBTYPE_MASK
#pragma push_macro("CPU_SUBTYPE_MC98601")
#undef CPU_SUBTYPE_MC98601
#pragma push_macro("CPU_SUBTYPE_MULTIPLE")
#undef CPU_SUBTYPE_MULTIPLE
#pragma push_macro("CPU_SUBTYPE_PENT")
#undef CPU_SUBTYPE_PENT
#pragma push_macro("CPU_SUBTYPE_PENTII_M3")
#undef CPU_SUBTYPE_PENTII_M3
#pragma push_macro("CPU_SUBTYPE_PENTII_M5")
#undef CPU_SUBTYPE_PENTII_M5
#pragma push_macro("CPU_SUBTYPE_PENTIUM_3")
#undef CPU_SUBTYPE_PENTIUM_3
#pragma push_macro("CPU_SUBTYPE_PENTIUM_3_M")
#undef CPU_SUBTYPE_PENTIUM_3_M
#pragma push_macro("CPU_SUBTYPE_PENTIUM_3_XEON")
#undef CPU_SUBTYPE_PENTIUM_3_XEON
#pragma push_macro("CPU_SUBTYPE_PENTIUM_4")
#undef CPU_SUBTYPE_PENTIUM_4
#pragma push_macro("CPU_SUBTYPE_PENTIUM_4_M")
#undef CPU_SUBTYPE_PENTIUM_4_M
#pragma push_macro("CPU_SUBTYPE_PENTIUM_M")
#undef CPU_SUBTYPE_PENTIUM_M
#pragma push_macro("CPU_SUBTYPE_PENTPRO")
#undef CPU_SUBTYPE_PENTPRO
#pragma push_macro("CPU_SUBTYPE_POWERPC_601")
#undef CPU_SUBTYPE_POWERPC_601
#pragma push_macro("CPU_SUBTYPE_POWERPC_602")
#undef CPU_SUBTYPE_POWERPC_602
#pragma push_macro("CPU_SUBTYPE_POWERPC_603")
#undef CPU_SUBTYPE_POWERPC_603
#pragma push_macro("CPU_SUBTYPE_POWERPC_603e")
#undef CPU_SUBTYPE_POWERPC_603e
#pragma push_macro("CPU_SUBTYPE_POWERPC_603ev")
#undef CPU_SUBTYPE_POWERPC_603ev
#pragma push_macro("CPU_SUBTYPE_POWERPC_604")
#undef CPU_SUBTYPE_POWERPC_604
#pragma push_macro("CPU_SUBTYPE_POWERPC_604e")
#undef CPU_SUBTYPE_POWERPC_604e
#pragma push_macro("CPU_SUBTYPE_POWERPC_620")
#undef CPU_SUBTYPE_POWERPC_620
#pragma push_macro("CPU_SUBTYPE_POWERPC_7400")
#undef CPU_SUBTYPE_POWERPC_7400
#pragma push_macro("CPU_SUBTYPE_POWERPC_7450")
#undef CPU_SUBTYPE_POWERPC_7450
#pragma push_macro("CPU_SUBTYPE_POWERPC_750")
#undef CPU_SUBTYPE_POWERPC_750
#pragma push_macro("CPU_SUBTYPE_POWERPC_970")
#undef CPU_SUBTYPE_POWERPC_970
#pragma push_macro("CPU_SUBTYPE_POWERPC_ALL")
#undef CPU_SUBTYPE_POWERPC_ALL
#pragma push_macro("CPU_SUBTYPE_SPARC_ALL")
#undef CPU_SUBTYPE_SPARC_ALL
#pragma push_macro("CPU_SUBTYPE_X86_64_ALL")
#undef CPU_SUBTYPE_X86_64_ALL
#pragma push_macro("CPU_SUBTYPE_X86_64_H")
#undef CPU_SUBTYPE_X86_64_H
#pragma push_macro("CPU_SUBTYPE_X86_ALL")
#undef CPU_SUBTYPE_X86_ALL
#pragma push_macro("CPU_SUBTYPE_X86_ARCH1")
#undef CPU_SUBTYPE_X86_ARCH1
#pragma push_macro("CPU_SUBTYPE_XEON")
#undef CPU_SUBTYPE_XEON
#pragma push_macro("CPU_SUBTYPE_XEON_MP")
#undef CPU_SUBTYPE_XEON_MP
#pragma push_macro("CPU_TYPE_ANY")
#undef CPU_TYPE_ANY
#pragma push_macro("CPU_TYPE_ARM")
#undef CPU_TYPE_ARM
#pragma push_macro("CPU_TYPE_ARM64")
#undef CPU_TYPE_ARM64
#pragma push_macro("CPU_TYPE_ARM64_32")
#undef CPU_TYPE_ARM64_32
#pragma push_macro("CPU_TYPE_I386")
#undef CPU_TYPE_I386
#pragma push_macro("CPU_TYPE_MC98000")
#undef CPU_TYPE_MC98000
#pragma push_macro("CPU_TYPE_POWERPC")
#undef CPU_TYPE_POWERPC
#pragma push_macro("CPU_TYPE_POWERPC64")
#undef CPU_TYPE_POWERPC64
#pragma push_macro("CPU_TYPE_SPARC")
#undef CPU_TYPE_SPARC
#pragma push_macro("CPU_TYPE_X86")
#undef CPU_TYPE_X86
#pragma push_macro("CPU_TYPE_X86_64")
#undef CPU_TYPE_X86_64
#pragma push_macro("VM_PROT_EXECUTE")
#undef VM_PROT_EXECUTE
#pragma push_macro("VM_PROT_READ")
#undef VM_PROT_READ
#pragma push_macro("VM_PROT_WRITE")
#undef VM_PROT_WRITE

#include <llvm/Object/MachO.h>

#pragma pop_macro("VM_PROT_WRITE")
#pragma pop_macro("VM_PROT_READ")
#pragma pop_macro("VM_PROT_EXECUTE")
#pragma pop_macro("CPU_TYPE_X86_64")
#pragma pop_macro("CPU_TYPE_X86")
#pragma pop_macro("CPU_TYPE_SPARC")
#pragma pop_macro("CPU_TYPE_POWERPC64")
#pragma pop_macro("CPU_TYPE_POWERPC")
#pragma pop_macro("CPU_TYPE_MC98000")
#pragma pop_macro("CPU_TYPE_I386")
#pragma pop_macro("CPU_TYPE_ARM64_32")
#pragma pop_macro("CPU_TYPE_ARM64")
#pragma pop_macro("CPU_TYPE_ARM")
#pragma pop_macro("CPU_TYPE_ANY")
#pragma pop_macro("CPU_SUBTYPE_XEON_MP")
#pragma pop_macro("CPU_SUBTYPE_XEON")
#pragma pop_macro("CPU_SUBTYPE_X86_ARCH1")
#pragma pop_macro("CPU_SUBTYPE_X86_ALL")
#pragma pop_macro("CPU_SUBTYPE_X86_64_H")
#pragma pop_macro("CPU_SUBTYPE_X86_64_ALL")
#pragma pop_macro("CPU_SUBTYPE_SPARC_ALL")
#pragma pop_macro("CPU_SUBTYPE_POWERPC_ALL")
#pragma pop_macro("CPU_SUBTYPE_POWERPC_970")
#pragma pop_macro("CPU_SUBTYPE_POWERPC_750")
#pragma pop_macro("CPU_SUBTYPE_POWERPC_7450")
#pragma pop_macro("CPU_SUBTYPE_POWERPC_7400")
#pragma pop_macro("CPU_SUBTYPE_POWERPC_620")
#pragma pop_macro("CPU_SUBTYPE_POWERPC_604e")
#pragma pop_macro("CPU_SUBTYPE_POWERPC_604")
#pragma pop_macro("CPU_SUBTYPE_POWERPC_603ev")
#pragma pop_macro("CPU_SUBTYPE_POWERPC_603e")
#pragma pop_macro("CPU_SUBTYPE_POWERPC_603")
#pragma pop_macro("CPU_SUBTYPE_POWERPC_602")
#pragma pop_macro("CPU_SUBTYPE_POWERPC_601")
#pragma pop_macro("CPU_SUBTYPE_PENTPRO")
#pragma pop_macro("CPU_SUBTYPE_PENTIUM_M")
#pragma pop_macro("CPU_SUBTYPE_PENTIUM_4_M")
#pragma pop_macro("CPU_SUBTYPE_PENTIUM_4")
#pragma pop_macro("CPU_SUBTYPE_PENTIUM_3_XEON")
#pragma pop_macro("CPU_SUBTYPE_PENTIUM_3_M")
#pragma pop_macro("CPU_SUBTYPE_PENTIUM_3")
#pragma pop_macro("CPU_SUBTYPE_PENTII_M5")
#pragma pop_macro("CPU_SUBTYPE_PENTII_M3")
#pragma pop_macro("CPU_SUBTYPE_PENT")
#pragma pop_macro("CPU_SUBTYPE_MULTIPLE")
#pragma pop_macro("CPU_SUBTYPE_MC98601")
#pragma pop_macro("CPU_SUBTYPE_MASK")
#pragma pop_macro("CPU_SUBTYPE_LIB64")
#pragma pop_macro("CPU_SUBTYPE_ITANIUM_2")
#pragma pop_macro("CPU_SUBTYPE_ITANIUM")
#pragma pop_macro("CPU_SUBTYPE_INTEL_MODEL_ALL")
#pragma pop_macro("CPU_SUBTYPE_INTEL_MODEL")
#pragma pop_macro("CPU_SUBTYPE_INTEL_FAMILY_MAX")
#pragma pop_macro("CPU_SUBTYPE_INTEL_FAMILY")
#pragma pop_macro("CPU_SUBTYPE_INTEL")
#pragma pop_macro("CPU_SUBTYPE_I386_ALL")
#pragma pop_macro("CPU_SUBTYPE_CELERON_MOBILE")
#pragma pop_macro("CPU_SUBTYPE_CELERON")
#pragma pop_macro("CPU_SUBTYPE_ARM_XSCALE")
#pragma pop_macro("CPU_SUBTYPE_ARM_V7S")
#pragma pop_macro("CPU_SUBTYPE_ARM_V7M")
#pragma pop_macro("CPU_SUBTYPE_ARM_V7K")
#pragma pop_macro("CPU_SUBTYPE_ARM_V7EM")
#pragma pop_macro("CPU_SUBTYPE_ARM_V7")
#pragma pop_macro("CPU_SUBTYPE_ARM_V6M")
#pragma pop_macro("CPU_SUBTYPE_ARM_V6")
#pragma pop_macro("CPU_SUBTYPE_ARM_V5TEJ")
#pragma pop_macro("CPU_SUBTYPE_ARM_V4T")
#pragma pop_macro("CPU_SUBTYPE_ARM_ALL")
#pragma pop_macro("CPU_SUBTYPE_ARM64_V8")
#pragma pop_macro("CPU_SUBTYPE_ARM64_ALL")
#pragma pop_macro("CPU_SUBTYPE_ARM64_32_V8")
#pragma pop_macro("CPU_SUBTYPE_ARM64E")
#pragma pop_macro("CPU_SUBTYPE_586")
#pragma pop_macro("CPU_SUBTYPE_486SX")
#pragma pop_macro("CPU_SUBTYPE_486")
#pragma pop_macro("CPU_SUBTYPE_386")
#pragma pop_macro("CPU_ARCH_MASK")
#pragma pop_macro("CPU_ARCH_ABI64_32")
#pragma pop_macro("CPU_ARCH_ABI64")
#pragma pop_macro("ARM_VFP_STATE")
#pragma pop_macro("ARM_THREAD_STATE_COUNT")
#pragma pop_macro("ARM_THREAD_STATE64_COUNT")
#pragma pop_macro("ARM_THREAD_STATE64")
#pragma pop_macro("ARM_THREAD_STATE")
#pragma pop_macro("ARM_EXCEPTION_STATE64")
#pragma pop_macro("ARM_EXCEPTION_STATE")
#pragma pop_macro("ARM_DEBUG_STATE")
