#!/usr/bin/env python3
"""Execute WAST JSON assertions through real product CLIs (ROS remains full-only).

Consumes the JSON corpus generated by check_wasm2_corpus.py. Success actions
share one module instance, including mutable globals, tables and memory. For a
stateful module only the prefix through its first trap is covered: fatal UWVM
traps cannot be resumed without losing their side effects. Foreign imports,
host-created non-null references, and later stateful actions are explicitly
reported as exclusions, never passes. Dedicated integration tests cover them.
"""
import argparse
import concurrent.futures
import json
from pathlib import Path
import resource
import subprocess
import tempfile


TYPES = {0x7f: 'i32', 0x7e: 'i64', 0x7d: 'f32', 0x7c: 'f64',
         0x7b: 'v128', 0x70: 'funcref', 0x6f: 'externref'}


class Reader:
    def __init__(self, data):
        self.data, self.pos = data, 0

    def byte(self):
        value = self.data[self.pos]
        self.pos += 1
        return value

    def uint(self):
        result = shift = 0
        while True:
            byte = self.byte()
            result |= (byte & 127) << shift
            if byte < 128:
                return result
            shift += 7

    def blob(self, size):
        result = self.data[self.pos:self.pos + size]
        self.pos += size
        return result

    def name(self):
        return self.blob(self.uint()).decode('utf-8')

    def limits(self):
        flags = self.uint()
        self.uint()
        if flags & 1:
            self.uint()

    def expression(self):
        while True:
            opcode = self.byte()
            if opcode == 0x0b:
                return
            if opcode in (0x41, 0x42, 0x23, 0xd0, 0xd2):
                self.uint()
            elif opcode in (0x43, 0x44):
                self.blob(4 if opcode == 0x43 else 8)
            elif opcode == 0xfd and self.uint() == 12:
                self.blob(16)
            else:
                raise ValueError(f'unsupported constant expression: {opcode}')


def interface(path):
    reader = Reader(path.read_bytes()[8:])
    types, funcs, globals_, exports, imports = [], [], [], {}, []
    stateful = False
    while reader.pos < len(reader.data):
        section = reader.byte()
        body = Reader(reader.blob(reader.uint()))
        if section == 1:
            for _ in range(body.uint()):
                assert body.byte() == 0x60
                params = [TYPES[body.byte()] for _ in range(body.uint())]
                results = [TYPES[body.byte()] for _ in range(body.uint())]
                types.append((params, results))
        elif section == 2:
            for _ in range(body.uint()):
                module, _name, kind = body.name(), body.name(), body.byte()
                imports.append(module)
                if kind == 0:
                    funcs.append(body.uint())
                elif kind == 1:
                    body.byte()
                    body.limits()
                    stateful = True
                elif kind == 2:
                    body.limits()
                    stateful = True
                elif kind == 3:
                    globals_.append((TYPES[body.byte()], body.byte()))
                    stateful = True
                else:
                    raise ValueError(kind)
        elif section == 3:
            funcs.extend(body.uint() for _ in range(body.uint()))
        elif section in (4, 5):
            stateful |= body.uint() != 0
        elif section == 6:
            count = body.uint()
            stateful |= count != 0
            for _ in range(count):
                globals_.append((TYPES[body.byte()], body.byte()))
                body.expression()
        elif section == 7:
            for _ in range(body.uint()):
                name, kind, index = body.name(), body.byte(), body.uint()
                if kind == 0:
                    exports[name] = ('func', types[funcs[index]])
                elif kind == 3:
                    exports[name] = ('global', globals_[index])
    return exports, imports, stateful


def quoted(text):
    return '"' + ''.join(f'\\{byte:02x}' for byte in text.encode('utf-8')) + '"'


def constant(value):
    kind, bits = value['type'], value['value']
    if kind in ('i32', 'i64'):
        return f'{kind}.const {bits}'
    if kind in ('f32', 'f64'):
        integer = 'i' + kind[1:]
        return f'{integer}.const {bits} {kind}.reinterpret_{integer}'
    if kind in ('funcref', 'externref') and bits == 'null':
        return 'ref.null ' + ('func' if kind == 'funcref' else 'extern')
    if kind == 'v128':
        lane = value['lane_type']
        if lane in ('f32', 'f64'):
            lane = 'i' + lane[1:]
        return f'v128.const {lane}x{len(bits)} ' + ' '.join(bits)
    raise ValueError('host-created reference')


def integer_check(kind, bits):
    width = int(kind[1:])
    if bits.startswith('nan:'):
        mask = (1 << (width - 1)) - 1
        canonical = 0x7fc00000 if width == 32 else 0x7ff8000000000000
        if bits == 'nan:canonical':
            return f'{kind}.const {mask} {kind}.and {kind}.const {canonical} {kind}.ne'
        return f'{kind}.const {canonical} {kind}.and {kind}.const {canonical} {kind}.ne'
    return f'{kind}.const {bits} {kind}.ne'


def check(value, local):
    kind, bits = value['type'], value['value']
    if kind in ('i32', 'i64'):
        return f'local.get {local} ' + integer_check(kind, bits) + ' if unreachable end'
    if kind in ('f32', 'f64'):
        integer = 'i' + kind[1:]
        return f'local.get {local} {integer}.reinterpret_{kind} ' + integer_check(integer, bits) + ' if unreachable end'
    if kind in ('funcref', 'externref') and bits == 'null':
        return f'local.get {local} ref.is_null i32.eqz if unreachable end'
    if kind == 'v128':
        lane = value['lane_type']
        width = int(lane[1:])
        extract = f'i{width}x{128 // width}.extract_lane' + ('_u' if width < 32 else '')
        integer = 'i64' if width == 64 else 'i32'
        return '\n'.join(f'local.get {local} {extract} {index} ' + integer_check(integer, bit) + ' if unreachable end'
                         for index, bit in enumerate(bits))
    raise ValueError('host-created reference')


def wrapper(exports, commands):
    imports, locals_, code = {}, [], []
    for command in commands:
        action = command['action']
        field = action['field']
        kind, signature = exports[field]
        key = (kind, field)
        if key not in imports:
            symbol = '$e' + str(len(imports))
            if kind == 'func':
                params, results = signature
                declaration = f'(func {symbol} (param {" ".join(params)}) (result {" ".join(results)}))'
            else:
                value_type, mutable = signature
                declaration = f'(global {symbol} ' + (f'(mut {value_type})' if mutable else value_type) + ')'
            imports[key] = (symbol, f'(import "spec_target" {quoted(field)} {declaration})')
        symbol = imports[key][0]
        code.extend(constant(value) for value in action.get('args', []))
        code.append(('call ' if kind == 'func' else 'global.get ') + symbol)
        result_types = signature[1] if kind == 'func' else [signature[0]]
        if command['type'] == 'assert_return':
            expected = command['expected']
            assert [v['type'] for v in expected] == result_types
            indices = []
            for value_type in result_types:
                indices.append(len(locals_))
                locals_.append(value_type)
            code.extend(f'local.set {index}' for index in reversed(indices))
            code.extend(check(value, index) for value, index in zip(expected, indices))
        else:
            code.extend('drop' for _ in result_types)
    return '(module\n' + '\n'.join(v[1] for v in imports.values()) + '\n(func (export "_start")\n' + ''.join(f'(local {t})' for t in locals_) + '\n' + '\n'.join(code) + '\n))\n'


SPECTEST = '''(module
  (global (export "global_i32") i32 (i32.const 666))
  (global (export "global_i64") i64 (i64.const 666))
  (global (export "global_f32") f32 (f32.const 666.6))
  (global (export "global_f64") f64 (f64.const 666.6))
  (global (export "global_v128") v128 (v128.const i32x4 666 666 666 666))
  (table (export "table") 10 20 funcref)
  (memory (export "memory") 1 2)
  (func (export "print")) (func (export "print_i32") (param i32))
  (func (export "print_i64") (param i64)) (func (export "print_f32") (param f32))
  (func (export "print_f64") (param f64))
  (func (export "print_i32_f32") (param i32 f32))
  (func (export "print_f64_f64") (param f64 f64)))'''


def main():
    resource.setrlimit(resource.RLIMIT_CORE, (0, 0))
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--corpus', type=Path, required=True)
    parser.add_argument('--full', type=Path, required=True)
    parser.add_argument('--ros', type=Path, required=True)
    parser.add_argument('--out', type=Path)
    parser.add_argument('--jobs', type=int, default=4)
    parser.add_argument('--filter', default='')
    parser.add_argument('--batch-size', type=int, default=256)
    parser.add_argument('--feature-mode', choices=('wasm2', 'wasm1p1', 'default'), default='wasm2')
    parser.add_argument('--full-mode', choices=('full', 'lazy'), default='full')
    parser.add_argument('--products', nargs='+', choices=('full', 'ros'), default=['full', 'ros'])
    args = parser.parse_args()
    if args.batch_size < 1:
        parser.error('--batch-size must be positive')
    out = args.out or Path(tempfile.mkdtemp(prefix='uwvm-wasm2-execution-', dir='/tmp'))
    out.mkdir(parents=True, exist_ok=True)
    def compile_wat(path, wat):
        path.with_suffix('.wat').write_text(wat)
        proc = subprocess.run(['wat2wasm', '--debug-names', '-', '-o', str(path)], input=wat.encode(), capture_output=True)
        if proc.returncode:
            raise RuntimeError(f'wrapper generation failed: {path}: {proc.stderr!r}')
    compile_wat(out / 'spectest.wasm', SPECTEST)
    cases, excluded = [], []
    for script in sorted(args.corpus.rglob('script.json')):
        relative = str(script.parent.relative_to(args.corpus))
        if args.filter and args.filter not in relative:
            continue
        commands = json.loads(script.read_text())['commands']
        if any(command['type'] == 'register' for command in commands):
            # Other instances can mutate a registered module's exports between its assertions.
            # Replaying only its own actions would manufacture failures (or false passes).
            excluded.append(dict(source=relative, actions=sum('action' in c for c in commands),
                                 reason='registered cross-module state requires a resident runner'))
            continue
        groups, current, named = [], None, {}
        for command in commands:
            if command['type'] == 'module':
                current = dict(path=script.parent / command['filename'], actions=[], line=command['line'])
                groups.append(current)
                if 'name' in command:
                    named[command['name']] = current
            elif 'action' in command:
                group = named.get(command['action'].get('module'), current)
                if group is not None:
                    group['actions'].append(command)
        for number, group in enumerate(groups):
            exports, imports, stateful = interface(group['path'])
            prefix, stopped = [], False
            label = relative.replace('/', '_') + f'-m{number}'
            if any(name != 'spectest' for name in imports):
                excluded.append(dict(case=label, actions=len(group['actions']), reason='foreign module imports'))
                continue
            def add(commands, trap=None):
                if not commands:
                    return
                name = label + '-' + str(len(cases))
                path = out / (name + '.wasm')
                compile_wat(path, wrapper(exports, commands))
                cases.append(dict(name=name, path=str(path), target=str(group['path'].resolve()),
                                  assertions=len(commands), trap=trap, source=relative,
                                  lines=[c['line'] for c in commands]))
            for command in group['actions']:
                if stopped:
                    excluded.append(dict(case=label, line=command['line'], reason='stateful action after fatal trap/unsupported reference'))
                    continue
                try:
                    wrapper(exports, [command])
                except ValueError as error:
                    excluded.append(dict(case=label, line=command['line'], reason=str(error)))
                    stopped = stateful
                    continue
                if command['type'] in ('assert_trap', 'assert_exhaustion'):
                    add(prefix + [command] if stateful else [command], command['text'])
                    stopped = stateful
                else:
                    prefix.append(command)
                    if not stateful and len(prefix) == args.batch_size:
                        add(prefix)
                        prefix = []
            add(prefix)
    (out / 'cases.json').write_text(json.dumps(dict(cases=cases, excluded=excluded), indent=2) + '\n')
    if not cases:
        raise RuntimeError('no execution cases selected')
    def run(job):
        case, product, compiler = job
        options = ['-Rcm', args.full_mode, '-Rcc', 'int' if compiler == 'int' else 'jit'] if product == 'full' else ['-Rint' if compiler == 'int' else '-Raot']
        feature_options = [] if args.feature_mode == 'default' else ['--wasm-feature-' + args.feature_mode]
        command = [str(getattr(args, product).resolve()), *options, '-Rct', '0', '-Rllvm-cache-path', 'disable', *feature_options,
                   '--wasm-preload-library', str(out / 'spectest.wasm'), 'spectest',
                   '--wasm-preload-library', case['target'], 'spec_target', '--run', case['path']]
        try:
            proc = subprocess.run(command, capture_output=True, timeout=60)
            status, log = proc.returncode, proc.stdout + proc.stderr
        except subprocess.TimeoutExpired as error:
            status, log = 124, (error.stdout or b'') + (error.stderr or b'')
        trap = case['trap']
        needles = {'unreachable': 'catch unreachable', 'out of bounds memory access': 'out of bounds',
                   'out of bounds table access': 'out of bounds', 'undefined element': 'out of bounds',
                   'uninitialized element': 'uninitialized', 'integer divide by zero': 'divide by zero',
                   'integer overflow': 'integer overflow', 'invalid conversion to integer': 'invalid conversion',
                   'indirect call type mismatch': 'signature mismatch', 'call stack exhausted': 'stack'}
        if trap is None:
            passed = status == 0
        else:
            needle = needles.get(trap, trap).encode()
            passed = status not in (0, 124) and b'Runtime crash' in log and needle in log
        name = case['name'] + '-' + product + '-' + compiler
        (out / (name + '.log')).write_bytes(log)
        result = dict(case=case['name'], product=product, mode=args.full_mode if product == 'full' else 'full', compiler=compiler, status=status,
                      assertions=case['assertions'], passed=passed, expected_trap=trap)
        if not passed:
            print(json.dumps(result), flush=True)
        return result
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as pool:
        results = list(pool.map(run, [(case, product, compiler) for case in cases
                                    for product in args.products for compiler in ('int', 'llvm')]))
    (out / 'results.json').write_text(json.dumps(results, indent=2) + '\n')
    failed = sum(not r['passed'] for r in results)
    print(json.dumps(dict(feature_mode=args.feature_mode, full_mode=args.full_mode, products=args.products, cases=len(cases), runs=len(results), failed=failed,
                          assertion_executions=sum(r['assertions'] for r in results), exclusions=len(excluded), out=str(out))))
    return 1 if failed else 0


if __name__ == '__main__':
    raise SystemExit(main())
