#pragma once
#if defined(__GNUC__) || defined(__clang__)
#pragma GCC system_header
#endif
/*
The private representation is audited against the official llvm-project
`release/15.x` through `main` history:
https://github.com/llvm/llvm-project/blob/main/libcxx/include/string
*/

namespace fast_io::details::string_hack
{

/*
libc++ 15 replaced the legacy capacity-mask representation with the bit-field
representation modeled below.  `_LIBCPP_VERSION` is an encoded release value
(for example, 15.0.7 is 15007), not a plain major version.  Releases 18 and 19
also generate `_LIBCPP_INSTRUMENTED_WITH_ASAN` with `#cmakedefine`, so a defined
macro can have no replacement tokens; only libc++ 20 and later guarantee the
0/1 form generated by `#cmakedefine01`.

Writing into spare string capacity is therefore admitted only for the audited
ABI and only when the installed libc++ was not configured to annotate strings.
This deliberately fails closed: an annotated string keeps bytes beyond its
logical end poisoned until libc++ publishes the new size, which is incompatible
with a stateless raw put-area cursor.
*/
inline constexpr bool standard_string_runtime_put_area_available{
#if _LIBCPP_VERSION < 15000
	false
#elif _LIBCPP_VERSION < 200000
#if defined(_LIBCPP_INSTRUMENTED_WITH_ASAN)
	false
#else
	true
#endif
#elif defined(_LIBCPP_INSTRUMENTED_WITH_ASAN) && _LIBCPP_INSTRUMENTED_WITH_ASAN
	false
#else
	true
#endif
};

template <class _CharT, class _Traits, class _Allocator>
struct
#if __has_cpp_attribute(__gnu__::__may_alias__)
	[[__gnu__::__may_alias__]]
#endif
	model
{
	typedef _Traits traits_type;
	typedef _CharT value_type;
	typedef _Allocator allocator_type;
	typedef ::std::allocator_traits<allocator_type> __alloc_traits;
	typedef typename __alloc_traits::size_type size_type;
	typedef typename __alloc_traits::difference_type difference_type;
	typedef value_type &reference;
	typedef value_type const &const_reference;
	typedef typename __alloc_traits::pointer pointer;
	typedef typename __alloc_traits::const_pointer const_pointer;
#ifdef _LIBCPP_ABI_ALTERNATE_STRING_LAYOUT
	struct __long
	{
		pointer __data_;
		size_type __size_;
		size_type __cap_ : sizeof(size_type) * CHAR_BIT - 1;
		size_type __is_long_ : 1;
	};

	enum
	{
		__min_cap = (sizeof(__long) - 1) / sizeof(value_type) > 2 ? (sizeof(__long) - 1) / sizeof(value_type) : 2
	};

	struct __short
	{
		value_type __data_[__min_cap];
		unsigned char __padding_[sizeof(value_type) - 1];
		unsigned char __size_ : 7;
		unsigned char __is_long_ : 1;
	};

#else

	struct __long
	{
		// libc++ uses a packed anonymous field group here to preserve its pre-bit-field ABI on targets such as AIX.
		struct _LIBCPP_PACKED
		{
			size_type __is_long_ : 1;
			size_type __cap_ : sizeof(size_type) * CHAR_BIT - 1;
		};
		size_type __size_;
		pointer __data_;
	};

	enum
	{
		__min_cap = (sizeof(__long) - 1) / sizeof(value_type) > 2 ? (sizeof(__long) - 1) / sizeof(value_type) : 2
	};

	struct __short
	{
		// Match libc++'s packed flag byte rather than relying on the host's default bit-field allocation unit.
		struct _LIBCPP_PACKED
		{
			unsigned char __is_long_ : 1;
			unsigned char __size_ : 7;
		};
		char __padding_[sizeof(value_type) - 1];
		value_type __data_[__min_cap];
	};

#endif // _LIBCPP_ABI_ALTERNATE_STRING_LAYOUT

	union __ulx
	{
		__long __lx;
		__short __lxx;
	};

	enum
	{
		__n_words = sizeof(__ulx) / sizeof(size_type)
	};

	struct __raw
	{
		size_type __words[__n_words];
	};

	struct __rep
	{
		union
		{
			__long __l;
			__short __s;
			__raw __r;
		};
	};
#ifdef _LIBCPP_COMPRESSED_PAIR
	_LIBCPP_COMPRESSED_PAIR(__rep, __rep_, allocator_type, __alloc_);
#else
	::std::__compressed_pair<__rep, allocator_type> __r_;
#endif
};

/// @brief Reinterprets an audited libc++ basic_string object as its matching private representation.
template <typename elem, typename traits, typename alloc>
inline decltype(auto) hack_rep(::std::basic_string<elem, traits, alloc> &str) noexcept
{
	using model_t = model<elem, traits, alloc>;
	static_assert(sizeof(model_t) == sizeof(::std::basic_string<elem, traits, alloc>) &&
				  alignof(model_t) == alignof(::std::basic_string<elem, traits, alloc>),
			  "libc++ changed basic_string's private representation; the fast_io model must be re-audited");
	using __rep = typename model_t::__rep;
#ifdef _LIBCPP_COMPRESSED_PAIR
	using alias_pointer
#if __has_cpp_attribute(__gnu__::__may_alias__)
		[[__gnu__::__may_alias__]]
#endif
		= __rep *;
	return *reinterpret_cast<alias_pointer>(reinterpret_cast<::std::byte *>(__builtin_addressof(str)) +
											__builtin_offsetof(model_t, __rep_));
#else
	using alias_pointer
#if __has_cpp_attribute(__gnu__::__may_alias__)
		[[__gnu__::__may_alias__]]
#endif
		= typename ::std::__compressed_pair<__rep, alloc> *;
	return reinterpret_cast<alias_pointer>(reinterpret_cast<::std::byte *>(__builtin_addressof(str)) +
										   __builtin_offsetof(model_t, __r_))
		->first();
#endif
}

/// @brief Publishes a new libc++ string size only for ABI and sanitizer configurations that permit raw spare-capacity writes.
template <typename elem, typename traits, typename alloc>
inline void set_size(::std::basic_string<elem, traits, alloc> &str,
					 typename ::std::basic_string<elem, traits, alloc>::size_type s) noexcept
{
	static_assert(standard_string_runtime_put_area_available,
				  "fast_io's libc++ string put-area model is unavailable for this libc++ ABI or sanitizer configuration");
	decltype(auto) __r_{hack_rep(str)};
	if (bool(__r_.__s.__is_long_))
	{
		__r_.__l.__size_ = s;
	}
	else
	{
		__r_.__s.__size_ = (unsigned char)(s);
	}
}

template <typename T>
inline constexpr void set_end_ptr(T &str, typename T::value_type *ptr) noexcept
{
	set_size(str, static_cast<::std::size_t>(ptr - str.data()));
}

template <typename T>
inline constexpr ::std::size_t local_capacity() noexcept
{
	using model_type = model<typename T::value_type, typename T::traits_type, typename T::allocator_type>;
	constexpr ::std::size_t mcapminus1{
		static_cast<::std::size_t>(model_type::__min_cap - static_cast<::std::size_t>(1u))};
	return mcapminus1;
}

} // namespace fast_io::details::string_hack
